In [1]:
import numpy as np

from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import csgraph_from_dense

# Типы и Структуры Данных. ЛР4
## Разреженные матрицы

Необходимо реализовать либо КРМ, либо РСФ: упаковку, распаковку, сложение двух матриц и произведение двух матриц.

В лабораторной не допускается сплошное извлечение элементов матриц (вида "извлечь элемент с координатами [i][j] из упакованной матрицы"), требуется использовать алгоритмы просмотра массива ненулевых элементов.

In [2]:
a = [    
        [4, 0, 0],  
        [0, 5, 0],  
        [0, 0, 6]  
    ]
   
count = 0
  
rows = len(a)
cols = len(a[0])
  
size = rows * cols
   
for i in range(0, rows):  
    for j in range(0, cols):  
        if(a[i][j] == 0):  
            count = count + 1

if(count > (size/2)):  
    print("Данная матрица разреженная")
else:  
    print("Данная матрица плотная")

Данная матрица разреженная


In [3]:
# create dense matrix
A = np.array([
    [1, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 1],
    [0, 0, 0, 2, 0, 0],
])

print(A)
print()

# calculate sparsity
sparsity = 1.0 - np.count_nonzero(A) / A.size
print(sparsity)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]

0.7222222222222222


In [4]:
# страница 23

In [5]:
JA = [10, 8, 2, 9, 4, 3, 1, 6, 5, 7]
IP = [2, 5, 7]

Для проверки результатов используем метод [csr_matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html#scipy.sparse.csr_matrix) (Compressed Sparse Row matrix) модуля [Sparse](https://docs.scipy.org/doc/scipy/reference/sparse.html) из библиотеки [SciPy](https://docs.scipy.org/doc/scipy/reference/index.html)

In [6]:
# dense to sparse 

# create dense matrix
A = np.array([
    [1, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 1],
    [0, 0, 0, 2, 0, 0],
])

print('Исходная матрица:')
print(A)
print()

# convert to sparse matrix (CSR method)
print('Упакованная матрица:')
S = csr_matrix(A)
print(S)
print()

# reconstruct dense matrix
print('Распакованная матрица:')
B = S.todense()
print(B)

Исходная матрица:
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]

Упакованная матрица:
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2

Распакованная матрица:
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [7]:
type(S)

scipy.sparse.csr.csr_matrix

In [8]:
# G_dense = np.array([[0, 2, 1],
#                     [2, 0, 0],
#                     [1, 0, 0]])
# G_masked = np.ma.masked_values(G_dense, 0)

# G_sparse = csr_matrix(G_dense)
# G_sparse.data

In [9]:
# G2_data = np.array([[np.inf, 2,      0     ],
#                     [2,      np.inf, np.inf],
#                     [0,      np.inf, np.inf]])
# G2_masked = np.ma.masked_invalid(G2_data)
# from scipy.sparse.csgraph import csgraph_from_dense
# # G2_sparse = csr_matrix(G2_data) would give the wrong result
# G2_sparse = csgraph_from_dense(G2_data, null_value=np.inf)
# G2_sparse.data